version: '3'

services:
  app:
    build:
      context: .
    image: 'farmacia_alp'
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - APP_ENV=local
      - APP_KEY=
      - APP_DEBUG=true
      - APP_URL=http://localhost:8000
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_DATABASE=farmacia
      - DB_USERNAME=root
      - DB_PASSWORD=delfin23
      - DB_PORT=3306

    depends_on:
      - db
    command: ["php", "artisan", "serve", "--host", "0.0.0.0"]
    networks:
      - app
  
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: farmacia
      MYSQL_USER: root
      MYSQL_PASSWORD: delfin23
      MYSQL_ROOT_PASSWORD: delfin23
    command: "--default-authentication-plugin=mysql_native_password"
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app

networks:
  app:
