version: '3.3'
services:
  server:
    build:
      context: .
    volumes:
      - ./:/var/www/html
      - ./000-default.conf:/etc/apache2/sites-enabled/000-default.conf
    ports:
      - "8080:80"
      - "4433:443"
    depends_on:
      - db
    command: "sh /server.sh"

  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    volumes:
      - ./data/data:/var/lib/mysql
      - ./data/logs:/var/log/mysql
    environment:
      - MYSQL_DATABASE=farmacia
      - MYSQL_USER=lean
      - MYSQL_PASSWORD=delfin2023
      - MYSQL_ROOT_PASSWORD=delfin23
