# Define la imagen base de PHP
FROM php:7.3-apache

# Establece el directorio de trabajo en el contenedor
WORKDIR /var/www/html

# Copia los archivos del proyecto al contenedor
COPY . .

# Actualiza el índice de paquetes y luego instala las dependencias necesarias
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    git \
    unzip \
    libzip-dev \
    && docker-php-ext-install zip pdo_mysql \
    && pecl install xdebug \
    && docker-php-ext-enable xdebug \
    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
    && composer install --no-scripts --no-autoloader --prefer-dist

# Habilita el módulo mod_rewrite de Apache
RUN a2enmod rewrite

# Establece las variables de entorno necesarias para la conexión con la base de datos
ENV DB_CONNECTION=mysql
ENV DB_HOST=db
ENV DB_PORT=3307
ENV DB_DATABASE=farmacia
ENV DB_USERNAME=root
ENV DB_PASSWORD=delfin23

# Instala el cliente de MySQL y establece las variables de entorno necesarias para el cliente de MySQL
RUN apt-get update && \
    apt-get install -y default-mysql-client && \
    echo "export MYSQL_PWD=${DB_PASSWORD}" >> /etc/apache2/envvars

# Expone el puerto 80
EXPOSE 80

# Ejecuta el comando de migración de la base de datos
CMD php artisan migrate && apache2-foreground